# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode7.2
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install xctool
# - gem install cocoapods 
# - pod install --project-directory=Example

script:
- xctool -project UnitKit.xcodeproj -scheme UnitKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
# - xctool test -project UnitKit.xcodeproj -scheme UnitKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
# - set -o pipefail && xctool test -project UnitKit.xcodeproj -scheme UnitKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint